### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c GOARCH=amd64 GOOS=linux go build -o build/s57-tiler  ./cmd/s57-tiler"

### ISSUE THREAD

**Issue by adam6806** [wdantuma/s57-tiler#2]
adam@openplotter42:~/s57-tiler $ sudo docker build . -t s57-tiler
[+] Building 153.2s (12/13)                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                  0.1s
 => => transferring dockerfile: 434B                                                                                  0.0s
 => [internal] load metadata for ghcr.io/osgeo/gdal:ubuntu-small-3.7.1                                                0.9s
 => [internal] load .dockerignore                                                                                     0.0s
 => => transferring context: 2B                                                                                       0.0s
 => [build 1/7] FROM ghcr.io/osgeo/gdal:ubuntu-small-3.7.1@sha256:25c22fd2d889a09362ec12b39ddf26530198a2943fbf8160c7  0.0s
 => [internal] load build context                                                                                     0.0s
 => => transferring context: 2.96kB                                                                                   0.0s
 => CACHED [stage-1 2/3] WORKDIR /app                                                                                 0.0s
 => CACHED [build 2/7] RUN apt-get update                                                                             0.0s
 => CACHED [build 3/7] RUN apt-get -y install libgdal-dev golang-go build-essential git                               0.0s
 => CACHED [build 4/7] WORKDIR /app                                                                                   0.0s
 => CACHED [build 5/7] COPY . .                                                                                       0.0s
 => CACHED [build 6/7] RUN go mod download                                                                            0.0s
 => ERROR [build 7/7] RUN GOARCH=amd64 GOOS=linux go build -o build/s57-tiler  ./cmd/s57-tiler                      152.0s
------                                                                                                                     
 > [build 7/7] RUN GOARCH=amd64 GOOS=linux go build -o build/s57-tiler  ./cmd/s57-tiler:                                   
43.31 # github.com/wdantuma/s57-tiler/s57/dataset                                                                          
43.31 s57/dataset/dataset.go:18:14: undefined: gdal.Envelope                                                               
43.31 s57/dataset/dataset.go:32:32: undefined: gdal.DataSource                                                             
43.31 s57/dataset/dataset.go:68:24: undefined: gdal.Envelope                                                               
43.31 s57/dataset/dataset.go:112:27: undefined: gdal.OpenDataSource
43.31 note: module requires Go 1.20
------
Dockerfile:7
--------------------
   5 |     COPY . .
   6 |     RUN go mod download
   7 | >>> RUN GOARCH=amd64 GOOS=linux go build -o build/s57-tiler  ./cmd/s57-tiler
   8 |     FROM ghcr.io/osgeo/gdal:ubuntu-small-3.7.1
   9 |     WORKDIR /app
--------------------
ERROR: failed to solve: process "/bin/sh -c GOARCH=amd64 GOOS=linux go build -o build/s57-tiler  ./cmd/s57-tiler" did not complete successfully: exit code: 2

**Comment by wdantuma** [comment]
Hi Adam,

 Can you give me some more info about you're setup ? 
```
docker version
docker info
```

**Comment by godind** [comment]
I get something similar

```
: => ERROR [build 7/7] RUN GOARCH=amd64 GOOS=linux go build -o build/s57-t  3.8s
------                                                                          
 > [build 7/7] RUN GOARCH=amd64 GOOS=linux go build -o build/s57-tiler  ./cmd/s57-tiler:                                                                        
1.961 # github.com/wdantuma/s57-tiler/s57/dataset                               
1.961 s57/dataset/dataset.go:18:14: undefined: gdal.Envelope                    
1.961 s57/dataset/dataset.go:32:32: undefined: gdal.DataSource                  
1.961 s57/dataset/dataset.go:68:24: undefined: gdal.Envelope
1.961 s57/dataset/dataset.go:112:27: undefined: gdal.OpenDataSource
1.961 note: module requires Go 1.20
------
Dockerfile:7
--------------------
   5 |     COPY . .
   6 |     RUN go mod download
   7 | >>> RUN GOARCH=amd64 GOOS=linux go build -o build/s57-tiler  ./cmd/s57-tiler
   8 |     FROM ghcr.io/osgeo/gdal:ubuntu-small-3.7.1
   9 |     WORKDIR /app
--------------------
ERROR: failed to solve: process "/bin/sh -c GOARCH=amd64 GOOS=linux go build -o build/s57-tiler  ./cmd/s57-tiler" did not complete successfully: exit code: 2
```

Docker info

```
docker info
Client:
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:26:02 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.31.0 (153195)
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:12 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
Client:
 Version:    26.1.4
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1-desktop.1
    Path:     /Users/godind/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1-desktop.1
    Path:     /Users/godind/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     /Users/godind/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/godind/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.24
    Path:     /Users/godind/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/godind/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.2.0
    Path:     /Users/godind/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/godind/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.9.3
    Path:     /Users/godind/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.31-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 2.357GiB
 Name: docker-desktop
 ID: 48c66f16-80c7-4e57-aa95-7b57cf171108
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/godind/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by wdantuma** [comment]
Has been fixed by providing a pre build docker image see readme
