### ISSUE TITLE
WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match 

### ISSUE THREAD

**Issue by 1629dill** [wdantuma/s57-tiler#4]
Was trying to install s57 tiler and received this error.
Do not know what to do to fix.

=> [internal] load build definition from Dockerfile                       0.1s
 => => transferring dockerfile: 434B                                       0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (li  0.1s
 => [internal] load metadata for ghcr.io/osgeo/gdal:ubuntu-small-3.7.1     0.6s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build context                                          0.1s
 => => transferring context: 2.96kB                                        0.1s
 => [build 1/7] FROM ghcr.io/osgeo/gdal:ubuntu-small-3.7.1@sha256:25c22fd  0.0s
 => CACHED [stage-1 2/3] WORKDIR /app                                      0.0s
 => CACHED [build 2/7] RUN apt-get update                                  0.0s
 => CACHED [build 3/7] RUN apt-get -y install libgdal-dev golang-go build  0.0s
 => CACHED [build 4/7] WORKDIR /app                                        0.0s
 => CACHED [build 5/7] COPY . .                                            0.0s
 => CACHED [build 6/7] RUN go mod download                                 0.0s
 => ERROR [build 7/7] RUN GOARCH=amd64 GOOS=linux go build -o build/s57-  56.8s
------                                                                          
 > [build 7/7] RUN GOARCH=amd64 GOOS=linux go build -o build/s57-tiler  ./cmd/s57-tiler:                                                                        
27.36 # github.com/wdantuma/s57-tiler/s57/dataset                               
27.36 s57/dataset/dataset.go:18:14: undefined: gdal.Envelope                    
27.36 s57/dataset/dataset.go:32:32: undefined: gdal.DataSource                  
27.36 s57/dataset/dataset.go:68:24: undefined: gdal.Envelope
27.36 s57/dataset/dataset.go:112:27: undefined: gdal.OpenDataSource
27.36 note: module requires Go 1.20
------

 1 warning found (use --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
Dockerfile:7
--------------------
   5 |     COPY . .
   6 |     RUN go mod download
   7 | >>> RUN GOARCH=amd64 GOOS=linux go build -o build/s57-tiler  ./cmd/s57-tiler
   8 |     FROM ghcr.io/osgeo/gdal:ubuntu-small-3.7.1
   9 |     WORKDIR /app
--------------------
ERROR: failed to solve: process "/bin/sh -c GOARCH=amd64 GOOS=linux go build -o build/s57-tiler  ./cmd/s57-tiler" did not complete successfully: exit code: 2
pi@openplotter:~/s57-tiler $ ^C

**Comment by wdantuma** [comment]
I've updated the README to use a pre-build docker image from the docker hub can you try that one ?

**Comment by wdantuma** [comment]
See #2
