### ISSUE TITLE
What is the format?

### ISSUE THREAD

**Issue by VladimirKalachikhin** [wdantuma/s57-tiler#6]
I created a tile set as described and displayed it in the FreeboardSK. It works.

But when I wanted to get information about the tile, I couldn't do anything:
```
$ ogrinfo 83.pbf 
ERROR 4: `83.pbf' not recognized as a supported file format.
ogrinfo failed - unable to open '83.pbf'.
```
What's wrong?

**Comment by wdantuma** [comment]
That's actually a GDAL related question not belonging here, you're version of ogrinfo could be missing MVT support for example. You can check the support with:
```
ogrinfo --formats|grep MVT
  MVT -vector- (rw+v): Mapbox Vector Tiles
```
The output of ogrinfo on a s57-tiler generated MVT tile should then look something like:
```
ogrinfo 331.pbf
INFO: Open of `331.pbf'
      using driver `MVT' successful.
1: UNSARE (Polygon)
2: FLODOC (Polygon)
3: DEPARE (Multi Polygon)
4: M_COVR (Polygon)
5: M_SREL (Multi Polygon)
6: PONTON (Polygon)
7: M_QUAL (Multi Polygon)
8: m_nsys (Polygon)
9: LNDARE (Multi Polygon)
```
